#!/usr/bin/env -S bash -e



# TODO(docker-volume): /root/.cache/pip
# TODO(docker-volume): /root/.cache/vcpkg
# TODO(docker-volume): /root/.cargo



# paths
PROJECT=/cpp-jam
VENV=$PROJECT.venv
BUILD=$PROJECT.build
VCPKG=/vcpkg



# DOCKER: FROM ubuntu:24.04 AS base

# apt install
apt update
DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends -y \
  autoconf \
  automake \
  build-essential \
  cargo \
  curl \
  git \
  libtool \
  ninja-build \
  pkg-config \
  python3 \
  python3-dev \
  python3-pip \
  python3-venv \
  unzip \
  zip \

# create python venv
python3 -m venv $VENV
PATH=$VENV/bin:$PATH

# install cmake
pip3 install cmake

# install vcpkg
export VCPKG_FORCE_SYSTEM_BINARIES=1
if [[ ! -e $VCPKG ]]; then
  git clone https://github.com/microsoft/vcpkg.git $VCPKG
fi
if [[ ! -e $VCPKG/vcpkg ]]; then
  $VCPKG/bootstrap-vcpkg.sh -disableMetrics
fi



# DOCKER: FROM base AS ci

# install project requirements
pip3 install asn1tools

# configure
rm -rf $BUILD
VCPKG_ROOT=$VCPKG cmake --preset=default -B $BUILD $PROJECT

# build
cmake --build $BUILD

# run tests
ctest --test-dir $BUILD
